/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_daytrip_shared_math_SunriseMath */

#ifndef _Included_com_daytrip_shared_math_SunriseMath
#define _Included_com_daytrip_shared_math_SunriseMath
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     com_daytrip_shared_math_SunriseMath
 * Method:    yawToFacePosition
 * Signature: (FFFFFF)V
 */
JNIEXPORT void JNICALL Java_com_daytrip_shared_math_SunriseMath_yawToFacePosition
  (JNIEnv *, jclass, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     com_daytrip_shared_math_SunriseMath
 * Method:    pitchToFacePosition
 * Signature: (FFFFFF)V
 */
JNIEXPORT void JNICALL Java_com_daytrip_shared_math_SunriseMath_pitchToFacePosition
  (JNIEnv *, jclass, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat);

#ifdef __cplusplus
}
#endif
#endif
